#!/bin/sh -l
#SBATCH -A morri353
#SBATCH --nodes=1
#SBATCH --tasks-per-node=20
#SBATCH --time=96:00:00
#SBATCH --job-name ShearDSMC

cd $SLURM_SUBMIT_DIR

cd ~/DSMC/ICS10/05
cd ./10
~/DSMC/build/DenseDSMC &
cd ../9
~/DSMC/build/DenseDSMC &
cd ../8
~/DSMC/build/DenseDSMC &
cd ../7
~/DSMC/build/DenseDSMC &
cd ../6
~/DSMC/build/DenseDSMC &
cd ../5
~/DSMC/build/DenseDSMC &
cd ../4
~/DSMC/build/DenseDSMC &
cd ../3
~/DSMC/build/DenseDSMC &
cd ../2
~/DSMC/build/DenseDSMC &

cd ~/DSMC/ICS10/10
cd ./10
~/DSMC/build/DenseDSMC &
cd ../9
~/DSMC/build/DenseDSMC &
cd ../8
~/DSMC/build/DenseDSMC &
cd ../7
~/DSMC/build/DenseDSMC &
cd ../6
~/DSMC/build/DenseDSMC &
cd ../5
~/DSMC/build/DenseDSMC &
cd ../4
~/DSMC/build/DenseDSMC &
cd ../3
~/DSMC/build/DenseDSMC &
cd ../2
~/DSMC/build/DenseDSMC &


wait
