#!/bin/sh -l
#SBATCH -A morri353
#SBATCH --nodes=1
#SBATCH --tasks-per-node=60
#SBATCH --time=96:00:00
#SBATCH --job-name USF2_DSMC

cd $SLURM_SUBMIT_DIR

cd ./Run_shear
cd ./030/99
../../../ShearDSMC >& out &
cd ../95
../../../ShearDSMC >& out &
cd ../90
../../../ShearDSMC >& out &
cd ../85
../../../ShearDSMC >& out &
cd ../80
../../../ShearDSMC >& out &
cd ../75
../../../ShearDSMC >& out &
cd ../70
../../../ShearDSMC >& out &
cd ../65
../../../ShearDSMC >& out &
cd ../60
../../../ShearDSMC >& out &

cd ../../035/99
../../../ShearDSMC >& out &
cd ../95
../../../ShearDSMC >& out &
cd ../90
../../../ShearDSMC >& out &
cd ../85
../../../ShearDSMC >& out &
cd ../80
../../../ShearDSMC >& out &
cd ../75
../../../ShearDSMC >& out &
cd ../70
../../../ShearDSMC >& out &
cd ../65
../../../ShearDSMC >& out &
cd ../60
../../../ShearDSMC >& out &

cd ../../040/99
../../../ShearDSMC >& out &
cd ../95
../../../ShearDSMC >& out &
cd ../90
../../../ShearDSMC >& out &
cd ../85
../../../ShearDSMC >& out &
cd ../80
../../../ShearDSMC >& out &
cd ../75
../../../ShearDSMC >& out &
cd ../70
../../../ShearDSMC >& out &
cd ../65
../../../ShearDSMC >& out &
cd ../60
../../../ShearDSMC >& out &

cd ../../045/99
../../../ShearDSMC >& out &
cd ../95
../../../ShearDSMC >& out &
cd ../90
../../../ShearDSMC >& out &
cd ../85
../../../ShearDSMC >& out &
cd ../80
../../../ShearDSMC >& out &
cd ../75
../../../ShearDSMC >& out &
cd ../70
../../../ShearDSMC >& out &
cd ../65
../../../ShearDSMC >& out &
cd ../60
../../../ShearDSMC >& out &

cd ../../050/99
../../../ShearDSMC >& out &
cd ../95
../../../ShearDSMC >& out &
cd ../90
../../../ShearDSMC >& out &
cd ../85
../../../ShearDSMC >& out &
cd ../80
../../../ShearDSMC >& out &
cd ../75
../../../ShearDSMC >& out &
cd ../70
../../../ShearDSMC >& out &
cd ../65
../../../ShearDSMC >& out &
cd ../60
../../../ShearDSMC >& out &

wait
