  MODULE PARTICLE
    IMPLICIT NONE

    INTEGER :: PIP
    DOUBLE PRECISION :: DIA, RHO, PVOL, PMASS, AR, sigma_c, lcycl, bmax
    DOUBLE PRECISION :: ALPHA_PP, ALPHA_PW
    DOUBLE PRECISION :: COR_PP, COR_PW
    double precision, dimension(3) :: mI
    DOUBLE PRECISION :: oI
	
    DOUBLE PRECISION, DIMENSION(:,:), ALLOCATABLE :: DES_POS_NEW, DES_VEL_NEW, DES_OMEGA_NEW
    DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: Er
    DOUBLE PRECISION :: Zr_ref, P1hit, delta_eps_max
	
    CONTAINS
	
  END MODULE PARTICLE